# Generated by Django 3.0 on 2023-01-01 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite_Recipts',
            new_name='Favorite_Recipe',
        ),
        migrations.RenameModel(
            old_name='Recipts',
            new_name='Recipe',
        ),
    ]
